### ISSUE TITLE
Theme name watcher error

### ISSUE THREAD

**Issue by jeangris** [denaro-org/v-charts2#1]
### Summary 简述
Vue 2 version: there is an issue on the watcher handler when the themeName changes.

Related code:
```js
    themeName(val) {
      themeChange(globalThis.initPayload, props);
    }
```
`globalThis.initPayload` does not seem to be defined:

**[Vue warn]: Error in callback for watcher "themeName": "TypeError: Cannot destructure property 'echarts' of 'initPayload' as it is undefined."**

I'm not sure what should be done to fix that, I did not find where globalThis was defined.

### Expect 期望结果
No error.

**Comment by vxhly** [comment]
Please provide a complete demonstration example for troubleshooting.

**Comment by jeangris** [comment]
Any change to theme-name will trigger the issue:

```html
<template>
  <ve-histogram :data="chartData"
                :theme-name="theme" />
</template>

<script>
import VeHistogram from '@v-charts2/histogram/lib/vue2/v-charts.histogram.es'

export default {
  components: {
    VeHistogram
  },
  data () {
    return {
      theme: 'echart',
      chartData: {
        columns: ['日期', '访问用户', '下单用户', '下单率'],
        rows: [
          {
            日期: '1/1',
            访问用户: 1393,
            下单用户: 1093,
            下单率: 0.32
          },
          {
            日期: '1/2',
            访问用户: 3530,
            下单用户: 3230,
            下单率: 0.26
          }
        ]
      }
    }
  },
  mounted () {
    setTimeout(() => {
      this.theme = 'echart-dark'
    }, 1000)
  }
}
</script>
```

**Comment by vxhly** [comment]
Thanks for your feedback, please try to download the latest version of the dependency package.

**Comment by jeangris** [comment]
Could you publish it on NPM? Thanks

**Comment by vxhly** [comment]
i 'm sorry! The release failed due to my work mistakes. I upgraded the packaging method of pnpm and pushed version 1.1.0. Please download it again. Thank you for your feedback.

**Comment by jeangris** [comment]
With the same code, I get:
 TypeError: Cannot read properties of undefined (reading 'undefined')
    at VueComponent.handler (v-charts.histogram.mjs?89ba:1938:1)

I think there is a typo in the code.
Here is something that seems to fix it:
```js
const themeChange = (initPayload, props2) => {
  let {
    echarts,
    options: { _once } // Should be options instead of option
  } = initPayload;
```

**Comment by vxhly** [comment]
Welcome PR.
