### ISSUE TITLE
K线图的界面的异常缩放图重叠

### ISSUE THREAD

**Issue by WoolenWang** [denaro-org/v-charts2#10]
### Summary 简述
界面缩放条都挤在一起了

![image](https://github.com/user-attachments/assets/0a012843-4715-48ec-b270-1dac4ab33d6a)

![image](https://github.com/user-attachments/assets/00822905-ced7-4db5-b54a-5d8e5bf53f0e)

### Expect 期望结果
![image](https://github.com/user-attachments/assets/da953613-f309-4b04-9055-e1c43f87e4e2)

**Comment by vxhly** [comment]
请查看 echarts 官方文档进行对应的修改配置,而不是修改K线图里的源代码,
