### ISSUE TITLE
有个watcher的问题，14个月之前就修复了，一直没发npm，发个包呗

### ISSUE THREAD

**Issue by Aolef** [denaro-org/v-charts2#3]

**Comment by vxhly** [comment]
已发布 v1.1.2 , 请更新依赖包之后再试试会不会报错,如果还是报错请提供详细的报错信息和示例

**Comment by Aolef** [comment]
组件的index.js中存在import './style/v-charts.css'，路径错误

**Comment by vxhly** [comment]
我想你是理解错了代码,这个文件在打包的时候会从 core 包拷贝到各个子包, 所以使用 lib 包是没有路径问题的

**Comment by Aolef** [comment]
哦，原来如此，那有可能是最新的包打包的时候脚本没有执行copy动作，因为使用1.1.2是会报路径错误的

**Comment by vxhly** [comment]
感谢你的反馈,我已经看到有几个包的 vite.config 没有配置拷贝,在 1.1.3 中修复该问题
