### ISSUE TITLE
最新版有时间可以更新下npm吗

### ISSUE THREAD

**Issue by Aolef** [denaro-org/v-charts2#7]

**Comment by vxhly** [comment]
请看一下更新日志 https://denaro-org.github.io/v-charts2/changelog/CHANGELOG.html

**Comment by Aolef** [comment]
现在的包好像不是最新的，两周前刚merge了一个打包优化的pr，楼主看下

**Comment by vxhly** [comment]
目前最新版本是 1.2.1， 请问您使用的版本号是哪一个，遇到了什么问题，之前提交的 PR 有审核过的已经合并代码了

**Comment by Aolef** [comment]
我之前用的1.1.3，目前npmjs仓库中最新版本为1.1.3，github上最新代码为1.2.1，期望将github上代码发布一版npm

**Comment by Aolef** [comment]
已找到最新版本，感谢
